version: '3'

services:
  airbnb:
    container_name: airbnb
    networks:
      wave-net:
        aliases:
          - airbnb
    build:
      dockerfile: Dockerfile
    ports:
      - 3200:3000
networks:
  wave-net:
    external: true
