version: '3'

services:
  airbnb:
    container_name: airbnb
    entrypoint:
    - npm
    - run
    - dev
    volumes:
    - ./app:/opt/app
    - ./public:/opt/public
    # image: airbnb
    networks:
      wave-net:
        aliases:
          - airbnb
    build:
      dockerfile: Dockerfile.local
    ports:
      - 3200:3000
networks:
  wave-net:
    external: true
