import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import localFont from '@next/font/local'
import './globals.css'
import Navbar from './components/navbar/navbar'
import ClientOnly from './components/clientonly'

// const inter = Inter({ subsets: ['latin'] })


// Font files can be colocated inside of `pages`
const local = localFont({ src: '../public/fonts/Inter-VariableFont_slnt,wght.ttf' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={local.className}>
        <ClientOnly>
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
